#!/usr/bin/env python3
"""Randomization-inference demo: channeling Fisher in a small experiment.

A runnable companion to docs/methods-reference.md (the inference section) and
the aer-robustness skill. It makes the Young (2019) "Channeling Fisher" point:
in small experiments where leverage is concentrated -- an unbalanced treatment
arm plus heavy-tailed, skewed outcomes -- the conventional robust-SE (HC)
t-test badly over-rejects a TRUE null, because the small arm's variance
estimate is built from a handful of skewed draws and is typically far too
small. Statistical significance then rides on which few influential
observations happen to land in the treated arm. The Fisher randomization test
re-randomizes the treatment labels and recomputes the SAME test statistic, so
its null distribution is generated by the experiment's own assignment
mechanism: its size is exact by construction, no matter how ugly the error
distribution is, and it still detects real effects.

The script uses a KNOWN data-generating process: N = 30 units with only 5
treated by complete randomization (each treated unit has leverage 1/5), and
demeaned lognormal errors whose heavy right tail concentrates the outcome
variance in a few observations. Under a true zero effect the HC1 robust
t-test rejects at more than twice its nominal 5%; the randomization test
using the same HC1 t-statistic rejects at 5%; and under a real effect the
randomization test retains power. A fourth, well-behaved homoskedastic-normal
control DGP verifies that the classical t-test machinery itself is correct
(size ~ 5%), so the over-rejection is attributable to the leverage-plus-skew
design, not to a coding error.

Run:  python3 randomization_inference_demo.py
Deps: numpy, matplotlib
      (all pinned in ../../templates/python/requirements.txt)

References: young_2019 in ../../references.bib.
See ../../docs/methods-reference.md for the per-stack tooling (ritest,
StatsPAI ri_test) and ../../skills/aer-robustness/SKILL.md for when referees
expect randomization inference alongside robust SEs.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _aer_numeric_check import numeric_check  # noqa: E402

SEED = 20260415
N = 30                   # units in the small experiment
N_TREAT = 5              # unbalanced arm: only 5 treated (leverage 1/5 each)
SIGMA_LOG = 1.0          # log-scale sd of the lognormal (heavy-tailed) errors
TAU_ALT = 3.0            # real treatment effect for the power experiment
REPS = 2000              # Monte Carlo panels per experiment
PERMS = 499              # random re-assignments per randomization test
ALPHA = 0.05             # nominal test size
T_CRIT = 2.0484          # Student-t 97.5% critical value, df = N-2 = 28
OUT = Path(__file__).resolve().parent / "output"

N_CTRL = N - N_TREAT     # control-arm size
HC1_SCALE = N / (N - 2)  # small-sample HC1 degrees-of-freedom correction
LOGN_MEAN = float(np.exp(SIGMA_LOG**2 / 2))  # E[exp(sigma*Z)], to demean errors


def hc1_tstats(y: np.ndarray, treat: np.ndarray) -> np.ndarray:
    """HC1 robust t-statistics for OLS of y on [1, D], vectorized over rows
    of ``treat`` (each row one assignment of exactly N_TREAT treated units).

    For the dummy regression the coefficient is the difference in means and
    the HC0 sandwich variance is SSE_T/n_T^2 + SSE_C/n_C^2 (within-group
    residual sums of squares); HC1 rescales by N/(N-2).
    """
    M = treat.astype(float)                      # (B, N) assignment matrix
    q = y * y
    s1 = M @ y                                   # treated sums
    q1 = M @ q                                   # treated sums of squares
    m1 = s1 / N_TREAT
    m0 = (y.sum() - s1) / N_CTRL
    sse1 = np.maximum(q1 - N_TREAT * m1**2, 0.0)
    sse0 = np.maximum((q.sum() - q1) - N_CTRL * m0**2, 0.0)
    var = HC1_SCALE * (sse1 / N_TREAT**2 + sse0 / N_CTRL**2)
    return (m1 - m0) / np.sqrt(var)


def classical_tstat(y: np.ndarray, treat: np.ndarray) -> float:
    """Classical (homoskedastic, pooled-variance) t-statistic on the dummy."""
    y1, y0 = y[treat], y[~treat]
    sse = float(((y1 - y1.mean()) ** 2).sum() + ((y0 - y0.mean()) ** 2).sum())
    var = sse / (N - 2) * (1.0 / len(y1) + 1.0 / len(y0))
    return float((y1.mean() - y0.mean()) / np.sqrt(var))


def ri_pvalue(y: np.ndarray, t_obs: float, rng: np.random.Generator) -> float:
    """Fisher randomization p-value: re-randomize the labels, recompute the
    SAME HC1 t-statistic, and rank |t_obs| in that permutation distribution."""
    perms = rng.random((PERMS, N)).argsort(axis=1) < N_TREAT
    t_perm = hc1_tstats(y, perms)
    return (1.0 + float((np.abs(t_perm) >= abs(t_obs)).sum())) / (PERMS + 1.0)


def run_leverage_experiment(rng: np.random.Generator, tau: float) -> dict:
    """Monte Carlo over REPS panels of the unbalanced heavy-tailed DGP:
    rejection rates of the HC1 t-test and the randomization test at 5%."""
    rej_hc = rej_ri = 0
    for _ in range(REPS):
        treat = rng.permutation(N) < N_TREAT
        e = np.exp(SIGMA_LOG * rng.normal(size=N)) - LOGN_MEAN
        y = tau * treat + e
        t_obs = float(hc1_tstats(y, treat[None, :])[0])
        rej_hc += abs(t_obs) > T_CRIT
        rej_ri += ri_pvalue(y, t_obs, rng) <= ALPHA
    return {"hc": rej_hc / REPS, "ri": rej_ri / REPS}


def run_control_experiment(rng: np.random.Generator) -> float:
    """Well-behaved homoskedastic-normal null DGP (same 5/25 split): the
    classical t-test has exact 5% size here, certifying the machinery."""
    rej = 0
    for _ in range(REPS):
        treat = rng.permutation(N) < N_TREAT
        y = rng.normal(size=N)
        rej += abs(classical_tstat(y, treat)) > T_CRIT
    return rej / REPS


def make_figure(null_m: dict, alt_m: dict, size_control: float) -> Path:
    OUT.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(7.5, 4.2))
    labels = ["HC1 t-test\n(true null,\nheavy tails)",
              "randomization\ntest (true null,\nheavy tails)",
              "classical t\n(true null,\nwell-behaved)",
              "randomization\ntest (real effect:\npower)"]
    vals = [null_m["hc"], null_m["ri"], size_control, alt_m["ri"]]
    colors = ["firebrick", "black", "steelblue", "darkorange"]
    ax.bar(labels, vals, color=colors)
    ax.axhline(ALPHA, linestyle="--", color="grey",
               label=f"nominal size = {ALPHA:.2f}")
    ax.set_ylabel(f"Rejection rate at nominal {ALPHA:.0%}")
    ax.set_title("Young (2019): robust-SE t over-rejects under leverage; "
                 "Fisher's test has exact size")
    ax.legend(frameon=False)
    fig.tight_layout()
    pdf = OUT / "randomization_inference.pdf"
    fig.savefig(pdf)
    fig.savefig(OUT / "randomization_inference.png", dpi=150)
    plt.close(fig)
    return pdf


def main() -> int:
    rng = np.random.default_rng(SEED)
    null_m = run_leverage_experiment(rng, tau=0.0)
    alt_m = run_leverage_experiment(rng, tau=TAU_ALT)
    size_control = run_control_experiment(rng)

    print("=" * 70)
    print("Channeling Fisher: randomization inference in a small experiment")
    print(f"  N={N} ({N_TREAT} treated)  lognormal errors (sigma={SIGMA_LOG:.0f})"
          f"  reps={REPS}  perms={PERMS}  seed={SEED}")
    print("=" * 70)
    print(f"  TRUE NULL, unbalanced heavy-tailed DGP (nominal size {ALPHA:.2f}):")
    print(f"    HC1 robust t-test rejects        {null_m['hc']:.3f}"
          f"   ({null_m['hc'] / ALPHA:.1f}x nominal -- over-rejection)")
    print(f"    randomization test rejects       {null_m['ri']:.3f}"
          f"   (exact by construction)")
    print(f"  REAL EFFECT tau={TAU_ALT:.0f}, same DGP:")
    print(f"    HC1 robust t-test rejects        {alt_m['hc']:.3f}"
          f"   (inflated by its size distortion)")
    print(f"    randomization test rejects       {alt_m['ri']:.3f}"
          f"   (power is retained)")
    print(f"  TRUE NULL, well-behaved control DGP:")
    print(f"    classical t-test rejects         {size_control:.3f}"
          f"   (machinery is correct; leverage+skew is the culprit)")
    print()
    print(f"  each treated unit carries leverage 1/{N_TREAT}, so the treated-arm")
    print("  variance estimate is built from 5 skewed draws and is usually far")
    print("  too small -- that is where the HC t-test's excess rejections come")
    print("  from. The randomization test conditions on the realized outcomes")
    print("  and re-draws only the labels, so its null distribution is correct")
    print("  no matter how heavy the tails.")

    pdf = make_figure(null_m, alt_m, size_control)
    print(f"\nFigure written to {pdf.relative_to(pdf.parents[2])}")

    # ---- assertions: the demo is also a test -------------------------
    # Each numeric_check pins an estimate to its known target and emits a
    # NUMERIC-CHECK line that scripts/run_example_smoke.py verifies.
    numeric_check("robust t-test over-rejects a true null", null_m["hc"], lo=0.09)
    numeric_check("randomization test has exact size", null_m["ri"],
                  target=ALPHA, tol=0.02)
    numeric_check("randomization test retains power", alt_m["ri"], lo=0.70)
    numeric_check("classical t-test has correct size in well-behaved control DGP",
                  size_control, lo=0.03, hi=0.07)
    print("\nAll assertions passed: with concentrated leverage and heavy tails "
          "the\nrobust-SE t-test over-rejects a true null, while the Fisher "
          "randomization\ntest keeps exact size and real power -- report it "
          "alongside robust SEs in\nsmall experiments.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
